Improve globat event collector
valensto/ostraka pull request #12
Opened 2023-06-06 12:06 UTC by valensto

2023-06-06 12:34 UTC, tzzed requested changes

2023-06-06 12:34 UTC, tzzed commented on internal/collector/types.go
> +func (e *event) marshall() []byte {
I think it will be better to implement `MarshalJSON()` and `UnmarshalJSON` that allows streaming decoding and encoding.

2023-06-06 12:34 UTC, tzzed commented on internal/dispatcher/dispatcher.go
> +		collect.WithOutput(output, marshalled).Send()
It's better to pass `b` as bytes

2023-06-06 12:50 UTC, valensto commented on internal/collector/types.go
> +func (e *event) marshall() []byte {
What do you think about give the responsability of doing this marshall to the consumer because maybe it will not always json needed ?

2023-06-07 18:05 UTC, merged

2023-06-07 18:05 UTC, tzzed approved these changes